<?php
namespace Tests\Filesystem\Adapters;

use \PHPUnit_Framework_TestCase;

use Molajo\Filesystem\Adapters\Local;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 20:58:10.
 */
class LocalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Local
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Local;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::write
     * @todo   Implement testWrite().
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::copy
     * @todo   Implement testCopy().
     */
    public function testCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::move
     * @todo   Implement testMove().
     */
    public function testMove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getList
     * @todo   Implement testGetList().
     */
    public function testGetList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::createDirectory
     * @todo   Implement testCreateDirectory().
     */
    public function testCreateDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::deleteDirectory
     * @todo   Implement testDeleteDirectory().
     */
    public function testDeleteDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getMetadata
     * @todo   Implement testGetMetadata().
     */
    public function testGetMetadata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::normalise
     * @todo   Implement testNormalise().
     */
    public function testNormalise()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::setPath
     * @todo   Implement testSetPath().
     */
    public function testSetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getAbsolutePath
     * @todo   Implement testGetAbsolutePath().
     */
    public function testGetAbsolutePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isAbsolute
     * @todo   Implement testIsAbsolute().
     */
    public function testIsAbsolute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isDirectory
     * @todo   Implement testIsDirectory().
     */
    public function testIsDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isFile
     * @todo   Implement testIsFile().
     */
    public function testIsFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isLink
     * @todo   Implement testIsLink().
     */
    public function testIsLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::exists
     * @todo   Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::size
     * @todo   Implement testSize().
     */
    public function testSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::connect
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getConnection
     * @todo   Implement testGetConnection().
     */
    public function testGetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::setConnection
     * @todo   Implement testSetConnection().
     */
    public function testSetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getRoot
     * @todo   Implement testGetRoot().
     */
    public function testGetRoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::setRoot
     * @todo   Implement testSetRoot().
     */
    public function testSetRoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::setPersistence
     * @todo   Implement testSetPersistence().
     */
    public function testSetPersistence()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getOwner
     * @todo   Implement testGetOwner().
     */
    public function testGetOwner()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getGroup
     * @todo   Implement testGetGroup().
     */
    public function testGetGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getCreateDate
     * @todo   Implement testGetCreateDate().
     */
    public function testGetCreateDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getAccessDate
     * @todo   Implement testGetAccessDate().
     */
    public function testGetAccessDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::getModifiedDate
     * @todo   Implement testGetModifiedDate().
     */
    public function testGetModifiedDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isReadable
     * @todo   Implement testIsReadable().
     */
    public function testIsReadable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isWriteable
     * @todo   Implement testIsWriteable().
     */
    public function testIsWriteable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::isExecutable
     * @todo   Implement testIsExecutable().
     */
    public function testIsExecutable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::chmod
     * @todo   Implement testChmod().
     */
    public function testChmod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapters\Local::touch
     * @todo   Implement testTouch().
     */
    public function testTouch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
