<?php
namespace Ftp;

use Molajo\Filesystem\Adapter as fsAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class FtpConnectTest extends Data
{
    private $class;

    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        parent::setUp();

        /** initialise call */
        $this->filesystem_type = 'Ftp';
        $this->action          = 'Read';

        return;
    }

    /**
     * Should default target directory to $this->path
     *
     * @covers Molajo\Filesystem\Type\Ftp::copyOrMove
     */
    public function testSuccessfulConnection()
    {
        $this->path            =   '/Data/test1.txt';

        $this->options = array(
            'username'          => 'test',
            'password'          => 'test',
            'host'              => 'localhost',
            'port'              => '21',
            'timeout'           => '15',
            'passive_mode'      => true,
            'initial_directory' => 'Data'
        );

        $adapter = new fsAdapter($this->action, $this->path, $this->filesystem_type, $this->options);

        var_dump($adapter);
        die;

        $this->assertEquals($this->calculateSize($this->path), $this->calculateSize($temp . '/test2.txt'));
        $this->assertGreaterThan(0, $this->calculateSize($temp . '/test2.txt'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
}
