<?php
namespace Local;

use Molajo\Filesystem\Adapter as adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class LocalMoveTest extends Data
{
    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        parent::setUp();

        /** initialise call */
        $this->handler = 'Local';
        $this->action  = 'Move';

        return;
    }

    /**
     * Should default target directory to $this->path
     *
     * @covers Molajo\Filesystem\Handler\Local::copyOrMove
     */
    public function testSuccessfulMoveSingleFileBlankDirectory()
    {
        $base = substr(__DIR__, 0, strlen(__DIR__) - 5);

        $temp = $base . '/.dev/Tests/Data/Testcases';

        $this->options = array(
            'target_directory' => '',
            'target_name'      => 'test2.txt',
            'replace'          => false,
            'target_handler'   => 'Local'
        );

        $this->path = $base . '/.dev/Tests/Data/Testcases/test1.txt';

        $adapter = new adapter($this->action, $this->path, $this->handler, $this->options);

        $this->assertfileExists($temp . '/test2.txt');
        $this->assertfileNotExists($this->path);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Handler\Local::copyOrMove
     */
    public function testSuccessfulMoveSingleFile()
    {
        $base = substr(__DIR__, 0, strlen(__DIR__) - 5);

        $temp = $base . '/.dev/Tests/Data/Testcases';

        $this->options = array(
            'target_directory' => '',
            'target_name'      => 'test2.txt',
            'replace'          => false,
            'target_handler'   => 'Local'
        );
        $this->path    = $base . '/.dev/Tests/Data/Testcases/test1.txt';

        $adapter = new adapter($this->action, $this->path, $this->handler, $this->options);

        $this->assertfileExists($temp . '/test2.txt');
        $this->assertfileNotExists($this->path);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Handler\Local::copyOrMove
     */
    public function testMoveSingleFolder()
    {
        $base = substr(__DIR__, 0, strlen(__DIR__) - 5);

        $temp = $base . '/.dev/Tests/Data';

        $this->options = array(
            'target_directory' => $temp,
            'target_name'      => 'didit',
            'replace'          => false,
            'target_handler'   => 'Local'
        );
        $this->path    = $base . '/.dev/Tests/Data/doit';

        $adapter = new adapter($this->action, $this->path, $this->handler, $this->options);

        $this->assertfileExists($temp . '/didit');
        $this->assertfileNotExists($this->path);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Handler\Local::copyOrMove
     */
    public function testMoveMultipleFolder()
    {
        $base = substr(__DIR__, 0, strlen(__DIR__) - 5);

        $temp = $base . '/.dev/Tests/Data';

        $this->options = array(
            'target_directory' => $temp,
            'target_name'      => 'Amy',
            'replace'          => false,
            'target_handler'   => 'Local'
        );
        $this->path    = $base . '/.dev/Tests/Data/Testcases';

        $adapter = new adapter($this->action, $this->path, $this->handler, $this->options);

        $this->assertfileExists($temp . '/Amy');
        $this->assertfileNotExists($this->path);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Handler\Local::copyOrMove
     * @expectedException Exception\Filesystem\RuntimeException
     */
    public function testNotAFile()
    {
        $base = substr(__DIR__, 0, strlen(__DIR__) - 5);

        $this->options = array(
            'target_directory' => $base . '/.dev/Tests/Data',
            'target_name'      => 'Amy',
            'replace'          => false,
            'target_handler'   => 'Local'
        );

        $this->path = $base . '/.dev/Tests/Dataeeeeee';
        $adapter    = new adapter($this->action, $this->path, $this->handler, $this->options);

        return;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
}
