<?php
namespace Ftp;

use Exception;
use Molajo\Filesystem\Exception\NotFoundException;
use Molajo\Filesystem\Exception\FilesystemException;

use Molajo\Filesystem\Adapter as fsAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class FtpReadTest extends Data
{
    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        parent::setUp();

        $this->filesystem_type = 'Ftp';
        $this->action          = 'Read';
        $this->path            = BASE_FOLDER . '/.dev/Tests/Data/test1.txt';
        $this->options         = array();
    }

    /**
     * Did this in Connect
     *
     * @covers Molajo\Filesystem\Type\Ftp::read
     */
    public function testReadSuccessful()
    {
        return;
    }

    /**
     * @covers Molajo\Filesystem\Type\Ftp::read
     * @expectedException InvalidArgumentException
     */
    public function testReadUnsuccessful()
    {
        $this->path = '/Data/testreally-is-not-there.txt';
        $adapter    = new fsAdapter($this->action, $this->path, $this->filesystem_type, $this->options = array());

        return;
    }

    /**
     * @covers Molajo\Filesystem\Type\Ftp::read
     * @expectedException InvalidArgumentException
     */
    public function testReadNotAFile()
    {
        $this->path = '';
        $adapter    = new fsAdapter($this->action, $this->path, $this->filesystem_type, $this->options = array());

        return;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
}
