<?php
namespace Tests\Filesystem;

use \PHPUnit_Framework_TestCase;
use Molajo\Filesystem\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class AdapterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Molajo\Filesystem\Adapter::setAdapter
     * @todo   Implement testSetAdapter().
     */
    public function testSetAdapter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapter::getAdapter
     * @todo   Implement testGetAdapter().
     */
    public function testGetAdapter()
    {

    }

    public function testRead()
    {
        $options = array('adapter_name' => 'Local');
        $path =  BASE_FOLDER . '/Tests/test1.txt';

        $adapter = new Adapter($path, $options = array());
        $this->object = $adapter->getAdapter();
        $data    = $this->object->read ();
        $this->assertEquals('yabba, dabba, doo', trim($data));
    }
}
