<?php
namespace Tests\Filesystem;

use \PHPUnit_Framework_TestCase;

use Molajo\Filesystem\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class AdapterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter Name
     */
    protected $adapter_name;

    /**
     * @var Path
     */
    protected $path;

    /**
     * @var Options
     */
    protected $options = array();

    /**
     * @var Filesystem
     */
    protected $filesystem;

    /**
     * Initialises Adapter
     */
    protected function setUp()
    {


        return;
    }


    /**
     * @covers Molajo\Filesystem\Adapter::setAdapter
     */
    public function testSetAdapter()
    {
        $this->adapter_name = 'Local';
        $this->action       = 'Read';
        $this->path         = BASE_FOLDER . '/Tests/test1.txt';
        $this->options      = array();

        $this->filesystem = new Adapter($this->adapter_name, $this->action, $this->path, $this->options = array());

        echo '<pre>';
        var_dump($this->filesystem);
        echo '</pre>';
        die;
        $this->assertObjectHasAttribute('options', $this->filesystem);
        $this->assertObjectHasAttribute('root', $this->filesystem);
        $this->assertObjectHasAttribute('persistence', $this->filesystem);
        $this->assertObjectHasAttribute('absolute_path', $this->filesystem);

        return;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
