<?php
namespace Tests\Filesystem;

use \PHPUnit_Framework_TestCase;

use Molajo\Filesystem\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class LocalWriteTest extends Data
{
    /**
     * @var Adapter Name
     */
    protected $adapter_name;

    /**
     * @var Action
     */
    protected $action;

    /**
     * @var Path
     */
    protected $path;

    /**
     * @var Options
     */
    protected $options = array();

    /**
     * @var Filesystem
     */
    protected $filesystem;

    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        parent::setUp();

        $this->adapter_name = 'Local';
        $this->action       = 'Write';
    }

    /**
     * @covers Molajo\Filesystem\Type\Local::write
     */
    public function testSuccessfulWrite()
    {
        if (file_exists(BASE_FOLDER . '/Tests' . '/' . 'test2.txt')) {
            \unlink(BASE_FOLDER . '/Tests' . '/' . 'test2.txt');
        }

        $temp = 'test2.txt';

        $this->options = array(
            'file'    => $temp,
            'replace' => false,
            'data'    => 'Here are the words to write.',
        );

        $this->path         = BASE_FOLDER . '/Tests';

        $connect = new Adapter($this->adapter_name, $this->path, $this->action, $this->options);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Type\Local::write
     */
    public function testSuccessfulRewrite()
    {
        $temp = 'test2.txt';

        $this->options = array(
            'file'    => $temp,
            'replace' => true,
            'data'    => 'Here are the words to write.',
        );

        $this->path         = BASE_FOLDER . '/Tests';

        $connect = new Adapter($this->adapter_name, $this->path, $this->action, $this->options);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Type\Local::write
     * @expectedException Molajo\Filesystem\Exception\FileException
     */
    public function testUnsuccessfulRewrite()
    {

        $temp = 'test2.txt';

        $this->options = array(
            'file'    => $temp,
            'replace' => false,
            'data'    => 'Here are the words to write.',
        );

        $this->path         = BASE_FOLDER . '/Tests';

        $connect = new Adapter($this->adapter_name, $this->path, $this->action, $this->options);

        return;

    }

    /**
     * @covers Molajo\Filesystem\Type\Local::write
     */
    public function testCreateSingleFolder()
    {
        $temp = 'OneMoreFolder';

        $this->options = array(
            'file'    => $temp,
            'replace' => false,
            'data'    => ''
        );


        $this->path = BASE_FOLDER . '/Tests/Data';

        $connect    = new Adapter($this->adapter_name, $this->path, $this->action, $this->options);

        return;
    }


    /**
     * rmdir($filePath);
     *  unlink($filePath);
     *
     * @covers Molajo\Filesystem\Type\Local::write
     */
    public function testCreateMultipleFolders()
    {
        $temp = 'sometimes.txt';

        $this->options = array(
            'file'    => $temp,
            'replace' => false,
            'data'    => 'Poop'
        );


        $this->path = BASE_FOLDER . '/Tests/Data/OneMoreFolder/Cats/love/Dogs';

        $connect    = new Adapter($this->adapter_name, $this->path, $this->action, $this->options);

        return;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

}
