<?php
namespace Tests\Filesystem;

use \PHPUnit_Framework_TestCase;

use Molajo\Filesystem\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class DeleteTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter Name
     */
    protected $adapter_name;

    /**
     * @var Action
     */
    protected $action;

    /**
     * @var Path
     */
    protected $path;

    /**
     * @var Options
     */
    protected $options = array();

    /**
     * @var Filesystem
     */
    protected $filesystem;

    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        $this->adapter_name = 'Local';
        $this->action       = 'Delete';
    }

    /**
     * @covers Molajo\Filesystem\Adapter::setAdapter
     */
    public function testDeleteFile()
    {
        $this->path         = BASE_FOLDER . '/Directorytree3/test3.txt';

        $connect = new Adapter($this->adapter_name, $this->path, $this->action, array());
        echo '<pre>';
        var_dump($connect);
        echo '</pre>';

        return;

    }

    /**
     * @covers Molajo\Filesystem\Adapter::setAdapter
     */
    public function testDeleteDirectory()
    {
        $this->path         = BASE_FOLDER . '/Directorytree3';

        $connect = new Adapter($this->adapter_name, $this->path, $this->action, array());
        echo '<pre>';
        var_dump($connect);
        echo '</pre>';

        return;

    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
