<?php
namespace Tests\Filesystem;

use \PHPUnit_Framework_TestCase;

use Molajo\Filesystem\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class WriteTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter Name
     */
    protected $adapter_name;

    /**
     * @var Action
     */
    protected $action;

    /**
     * @var Path
     */
    protected $path;

    /**
     * @var Options
     */
    protected $options = array();

    /**
     * @var Filesystem
     */
    protected $filesystem;

    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        $this->adapter_name = 'Local';
        $this->action       = 'Write';
        $this->path         = BASE_FOLDER . '/Tests';

        $this->options      = array(
            'file' => 'test2.txt',
            'data' => 'Here are the words to write.',
            'replace' => true
        );
    }

    /**
     * @covers Molajo\Filesystem\Adapter::setAdapter
     */
    public function testSuccessfulWrite()
    {
        $connect = new Adapter($this->adapter_name, $this->path, $this->action, $this->options);
        echo '<pre>';
        var_dump($connect);
        echo '</pre>';

        return;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
