<?php
namespace Local;

use Exception;
use Molajo\Filesystem\Exception\FilesystemException;
use Molajo\Filesystem\Exception\LocalFilesystemException;
use Molajo\Filesystem\Connection;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 06:27:20.
 */
class LocalReadTest extends Data
{
    /**
     * @var $adapter Object
     */
    protected $adapter;

    /**
     * Initialises Adapter
     */
    protected function setUp()
    {
        parent::setUp();

        $this->filesystem_type = 'Local';
        $this->action          = 'Read';
        $this->path            = BASE_FOLDER . '/.dev/Tests/Data/test1.txt';
        $this->options         = array();

        $this->adapter = new Connection();
    }

    /**
     * @covers Molajo\Filesystem\Type\Local::read
     */
    public function testReadSuccessful()
    {
        $results = $this->adapter->read($this->path);
        $this->assertEquals('yabba, dabba, doo', trim($results));

        return;
    }

    /**
     * @covers Molajo\Filesystem\Type\Local::read
     * @expectedException Molajo\Filesystem\Exception\FilesystemException
     */
    public function testReadUnsuccessful()
    {
        $this->path = BASE_FOLDER . '/.dev/Tests/Data/testreally-is-not-there.txt';
        $results = $this->adapter->read($this->path);

        return;
    }

    /**
     * @covers Molajo\Filesystem\Type\Local::read
     * @expectedException Molajo\Filesystem\Exception\FilesystemException
     */
    public function testReadNotAFile()
    {
        $this->path = BASE_FOLDER . '/.dev/Tests';
        $results = $this->adapter->read($this->path);

        return;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
}
